[
   {
      "name":"${container_name}",
      "image":"${container_image}",
      "essential":true,
      "portMappings":[
         {
            "containerPort":${container_port},
            "hostPort":${container_port}
         }
      ]
   }
]